import type { Product, Exhibitor } from '@/types'

// ── Mock product data (replace with real API / CMS) ──────────────────────────
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: 'AI 心臟風險評估平台',
    company: '奧克泰醫療科技',
    booth: 'M820',
    floor: '4F',
    scene: '心血管照護',
    sceneEn: 'Cardiovascular',
    type: 'AI 診斷',
    problem: '協助醫師在 3 分鐘內完成十年心臟病風險評估，降低漏診率 42%',
    isSNQ: true,
    isNew: false,
    tags: [],
  },
  {
    id: 'p002',
    name: '精準定位手術導航系統',
    company: '宸鑫醫療儀器',
    booth: 'N310',
    floor: '4F',
    scene: 'AI 影像診斷',
    sceneEn: 'AI Imaging',
    type: '手術輔助',
    problem: '亞毫米精度實時導航，縮短手術時間 30%，降低術後併發症',
    isSNQ: false,
    isNew: true,
    tags: [],
  },
  {
    id: 'p003',
    name: '遠距居家照護監測系統',
    company: '薈康科技',
    booth: 'A215',
    floor: '1F',
    scene: '高齡照護',
    sceneEn: 'Elderly Care',
    type: '遠距照護',
    problem: '整合穿戴裝置與 AI 異常偵測，24hr 守護獨居長者安全',
    isSNQ: false,
    isNew: false,
    tags: [],
  },
  {
    id: 'p004',
    name: '智慧胃鏡 AI 輔助判讀系統',
    company: '明鏡醫療科技',
    booth: 'B108',
    floor: '2F',
    scene: 'AI 影像診斷',
    sceneEn: 'AI Imaging',
    type: 'AI 診斷',
    problem: '即時辨識胃部病變，早期胃癌偵測率提升至 96.3%',
    isSNQ: true,
    isNew: false,
    tags: [],
  },
  {
    id: 'p005',
    name: '慢性病智慧管理雲端平台',
    company: '鉅晟數位健康',
    booth: 'C330',
    floor: '3F',
    scene: '慢病管理',
    sceneEn: 'Chronic Disease',
    type: '健康管理',
    problem: '整合血糖、血壓、用藥紀錄，個人化衛教與主動預警通知',
    isSNQ: false,
    isNew: true,
    tags: [],
  },
  {
    id: 'p006',
    name: '手術機器人輔助訓練模擬器',
    company: '元心科技',
    booth: 'D220',
    floor: '4F',
    scene: '手術導航',
    sceneEn: 'Surgical Nav',
    type: '醫療訓練',
    problem: '高保真度腹腔鏡模擬，住院醫師技能培訓時間縮短 40%',
    isSNQ: false,
    isNew: false,
    tags: [],
  },
]

// ── Mock exhibitor data ───────────────────────────────────────────────────────
export const MOCK_EXHIBITORS: Exhibitor[] = [
  {
    id: 'e001',
    name: '奧克泰醫療科技',
    nameEn: 'Octek Medical Technology',
    booth: 'M820',
    floor: '4F',
    scenes: ['心血管照護', 'AI 診斷'],
    productCount: 4,
    isSNQ: true,
  },
  {
    id: 'e002',
    name: '宸鑫醫療儀器',
    nameEn: 'ChenXin Medical Instruments',
    booth: 'N310',
    floor: '4F',
    scenes: ['AI 影像診斷', '手術導航'],
    productCount: 3,
    isSNQ: false,
  },
  {
    id: 'e003',
    name: '薈康科技',
    nameEn: 'HuiKang Technology',
    booth: 'A215',
    floor: '1F',
    scenes: ['高齡照護', '遠距醫療'],
    productCount: 5,
    isSNQ: false,
  },
  {
    id: 'e004',
    name: '明鏡醫療科技',
    nameEn: 'ClearMirror MedTech',
    booth: 'B108',
    floor: '2F',
    scenes: ['AI 影像診斷', '內視鏡'],
    productCount: 2,
    isSNQ: true,
  },
]
